stages:
  ingest_data:
    cmd: python src/ingestion.py
    deps:
      - src/ingestion.py
    outs:
      - src/data/raw/stock.csv
      - src/data/raw/news.json
      - src/data/raw/ingestion_summary.json
