name: CI/CD Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests (optional)
        run: |
          echo "Running tests..."
          pytest || echo "No tests found, skipping."

      - name: Run DVC + MLflow pipeline
        run: |
          dvc pull   # pulls data from remote
          python3 ingestion.py
          python3 preprocessing.py
          python3 model.py

      - name: Build Docker image
        run: docker build -t sumitdohanropar/mtp:latest .

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Push Docker image
        run: docker push sumitdohanropar/mtp:latest

      - name: Run Docker Compose (App + MLflow)
        run: |
          docker-compose up -d
